In [ ]:
import numpy as np
import pandas as pd

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
%matplotlib inline
import matplotlib.pyplot as plt

## Задания для самостоятельного выполнения  

# Задания по Numpy

1. С помощью массивов numpy создайте таблицу умножения.

In [ ]:
np.arange(1, 10)*np.arange(1, 10).reshape(-1, 1)


array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9],
       [ 2,  4,  6,  8, 10, 12, 14, 16, 18],
       [ 3,  6,  9, 12, 15, 18, 21, 24, 27],
       [ 4,  8, 12, 16, 20, 24, 28, 32, 36],
       [ 5, 10, 15, 20, 25, 30, 35, 40, 45],
       [ 6, 12, 18, 24, 30, 36, 42, 48, 54],
       [ 7, 14, 21, 28, 35, 42, 49, 56, 63],
       [ 8, 16, 24, 32, 40, 48, 56, 64, 72],
       [ 9, 18, 27, 36, 45, 54, 63, 72, 81]])

2. Создайте функцию, которая принимает как аргументы целое число N и первый элемент (вещественное число el1), и разность (вещественное число d) и создает матрицу по диагонали, которой распологаются первые N членов арифметической прогрессии.

In [ ]:
def mat(N, el1, d):
  n = el1 + (N - 1) * d
  diagl = np.arange(el1, (n + 1), d)
  return np.diag(diagl)

In [ ]:
mat(3, 1, 4)

array([[1, 0, 0],
       [0, 5, 0],
       [0, 0, 9]])

3. Сгенерируйте средствами numpy матрицу А 5 на 5, содержащую последовательные числа от 1 до 25. Используя срезы извлеките в плоский массив все нечетные элементы этой матрицы.


In [ ]:
A = np.arange(1,26).reshape(5,5)
A[A % 2 != 0]

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25])

4. Создайте двумерный массив, содержащий единицы на границе и нули внутри.

In [ ]:
M = np.zeros((5,5), int)
M[::4, :] = 1
M[:, ::4] = 1
M

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]])

5. Создайте две матрицы размером (5,5). Одна матрица содержит 5 в шахматном порядке как в задаче домашнего задания, другая имеет треугольную форму содержащую 5 на основной диагонали и в позициях выше ее, а ниже все 0. Посчитайте их детерминант и найдите обратные матрицы.

In [ ]:
B1 = np.zeros((5,5), int)
B1[::2, ::2] = 5
B1[1::2, 1::2] = 5
B1

array([[5, 0, 5, 0, 5],
       [0, 5, 0, 5, 0],
       [5, 0, 5, 0, 5],
       [0, 5, 0, 5, 0],
       [5, 0, 5, 0, 5]])

In [ ]:
B = np.ones((5,5))
B2 = np.triu(B, k = 0)*5
B2

array([[5., 5., 5., 5., 5.],
       [0., 5., 5., 5., 5.],
       [0., 0., 5., 5., 5.],
       [0., 0., 0., 5., 5.],
       [0., 0., 0., 0., 5.]])

In [ ]:
np.linalg.det(B1), np.linalg.det(B2)

(0.0, 3124.999999999999)

In [ ]:
np.linalg.inv(B2)

array([[ 0.2, -0.2,  0. ,  0. ,  0. ],
       [ 0. ,  0.2, -0.2,  0. ,  0. ],
       [ 0. ,  0. ,  0.2, -0.2,  0. ],
       [ 0. ,  0. ,  0. ,  0.2, -0.2],
       [ 0. ,  0. ,  0. ,  0. ,  0.2]])

# Задания по Pandas


6. С помощью pandas загрузите датасет для предсказания цены квартиры, прилагающийся к этой работе.

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/мо/data.csv')
df

Id  DistrictId  Rooms      Square  LifeSquare  KitchenSquare  Floor  \
0     11809          27    3.0  115.027311         NaN           10.0      4   
1      3013          22    1.0   39.832524   23.169223            8.0      7   
2      8215           1    3.0   78.342215   47.671972           10.0      2   
3      2352           1    1.0   40.409907         NaN            1.0     10   
4     13866          94    2.0   64.285067   38.562517            9.0     16   
...     ...         ...    ...         ...         ...            ...    ...   
9995   1260          61    2.0   49.090728   33.272626            6.0      3   
9996  16265          27    2.0   64.307684   37.038420            9.0     13   
9997   2795         178    1.0   29.648057   16.555363            5.0      3   
9998  14561          21    1.0   32.330292   22.326870            5.0      3   
9999   7202          94    1.0   35.815476   22.301367            6.0      9   

      HouseFloor  HouseYear  Ecology_1 Ecology_2 Ecology_3  Social_1  \
0           10.0       2014   0.075424         B         B        11   
1            8.0       1966   0.118537         B         B        30   
2           17.0       1988   0.025609         B         B        33   
3           22.0       1977   0.007122         B         B         1   
4           16.0       1972   0.282798         B         B        33   
...          ...        ...        ...       ...       ...       ...   
9995        12.0       1981   0.300323         B         B        52   
9996         0.0       1977   0.072158         B         B         2   
9997         5.0       1958   0.460556         B         B        20   
9998         9.0       1969   0.194489         B         B        47   
9999         9.0       1975   0.127376         B         B        43   

      Social_2  Social_3  Healthcare_1  Helthcare_2  Shops_1 Shops_2  \
0         3097         0           NaN            0        0       B   
1         6207         1        1183.0            1        0       B   
2         5261         0         240.0            3        1       B   
3          264         0           NaN            0        1       B   
4         8667         2           NaN            0        6       B   
...        ...       ...           ...          ...      ...     ...   
9995     10311         6           NaN            1        9       B   
9996       629         1           NaN            0        0       A   
9997      4386        14           NaN            1        5       B   
9998      8004         3         125.0            3        5       B   
9999      8429         3           NaN            3        9       B   

              Price  
0     305018.871089  
1     177734.553407  
2     282078.720850  
3     168106.007630  
4     343995.102962  
...             ...  
9995  119367.455796  
9996  199715.148807  
9997  165953.912580  
9998  171842.411855  
9999  177685.627486  

[10000 rows x 20 columns]

7. Выведите на экран несколько первых и несколько последний строк файла.



In [ ]:
df.head(3)

Id  DistrictId  Rooms      Square  LifeSquare  KitchenSquare  Floor  \
0  11809          27    3.0  115.027311         NaN           10.0      4   
1   3013          22    1.0   39.832524   23.169223            8.0      7   
2   8215           1    3.0   78.342215   47.671972           10.0      2   

   HouseFloor  HouseYear  Ecology_1 Ecology_2 Ecology_3  Social_1  Social_2  \
0        10.0       2014   0.075424         B         B        11      3097   
1         8.0       1966   0.118537         B         B        30      6207   
2        17.0       1988   0.025609         B         B        33      5261   

   Social_3  Healthcare_1  Helthcare_2  Shops_1 Shops_2          Price  
0         0           NaN            0        0       B  305018.871089  
1         1        1183.0            1        0       B  177734.553407  
2         0         240.0            3        1       B  282078.720850

In [ ]:
df.tail(3)

Id  DistrictId  Rooms     Square  LifeSquare  KitchenSquare  Floor  \
9997   2795         178    1.0  29.648057   16.555363            5.0      3   
9998  14561          21    1.0  32.330292   22.326870            5.0      3   
9999   7202          94    1.0  35.815476   22.301367            6.0      9   

      HouseFloor  HouseYear  Ecology_1 Ecology_2 Ecology_3  Social_1  \
9997         5.0       1958   0.460556         B         B        20   
9998         9.0       1969   0.194489         B         B        47   
9999         9.0       1975   0.127376         B         B        43   

      Social_2  Social_3  Healthcare_1  Helthcare_2  Shops_1 Shops_2  \
9997      4386        14           NaN            1        5       B   
9998      8004         3         125.0            3        5       B   
9999      8429         3           NaN            3        9       B   

              Price  
9997  165953.912580  
9998  171842.411855  
9999  177685.627486

8. Выведите с помощью методов pandas основные количественные параметры датасета: количество строк и столбцов, тип данных каждого поля, количество значений в каждом столбце, шкала измерения каждого численного поля.

In [ ]:
print('Количество строк:', df.shape[0])
print('Количество столбцов:', df.shape[1])

Количество строк: 10000
Количество столбцов: 20


In [ ]:
print('Типы данных каждого поля (шкалы измерений)')
df.dtypes

Типы данных каждого поля (шкалы измерений)


Id                 int64
DistrictId         int64
Rooms            float64
Square           float64
LifeSquare       float64
KitchenSquare    float64
Floor              int64
HouseFloor       float64
HouseYear          int64
Ecology_1        float64
Ecology_2         object
Ecology_3         object
Social_1           int64
Social_2           int64
Social_3           int64
Healthcare_1     float64
Helthcare_2        int64
Shops_1            int64
Shops_2           object
Price            float64
dtype: object

In [ ]:
print('Количество значений в каждом столбце:')
df.count()

Количество значений в каждом столбце:


Id               10000
DistrictId       10000
Rooms            10000
Square           10000
LifeSquare        7887
KitchenSquare    10000
Floor            10000
HouseFloor       10000
HouseYear        10000
Ecology_1        10000
Ecology_2        10000
Ecology_3        10000
Social_1         10000
Social_2         10000
Social_3         10000
Healthcare_1      5202
Helthcare_2      10000
Shops_1          10000
Shops_2          10000
Price            10000
dtype: int64

9. Удалите из таблицы столбцы, содержащие идентификаторы, переименуйте все оставшиеся названия колонок на русском языке.

In [ ]:
df.drop(labels = ['Id', 'DistrictId'], axis = 1, inplace=True)
df.head(2)

Rooms      Square  LifeSquare  KitchenSquare  Floor  HouseFloor  HouseYear  \
0    3.0  115.027311         NaN           10.0      4        10.0       2014   
1    1.0   39.832524   23.169223            8.0      7         8.0       1966   

   Ecology_1 Ecology_2 Ecology_3  Social_1  Social_2  Social_3  Healthcare_1  \
0   0.075424         B         B        11      3097         0           NaN   
1   0.118537         B         B        30      6207         1        1183.0   

   Helthcare_2  Shops_1 Shops_2          Price  
0            0        0       B  305018.871089  
1            1        0       B  177734.553407

In [ ]:
df.rename(columns={'Rooms':'Количество комнат',
           'Square':'Площадь',
           'LifeSquare':'Жилая площадь',
           'KitchenSquare':'Площадь кухни',
           'Floor':'Этаж',
           'HouseFloor':'Количество квартир на этаже',
           'HouseYear':'Год постройки дома',
           'Ecology_1':'Экология_1',
           'Ecology_2':'Экология_2',
           'Ecology_3':'Экология_3',
           'Social_1':'Социальное_1',
           'Social_2':'Социальное_2',
           'Social_3':'Социальное_3',
           'Healthcare_1':'Здоровье_1',
           'Helthcare_2':'Здоровье_2',
           'Shops_1':'Магазины_1',
           'Shops_2':'Магазины_2',
           'Price':'Цена'}, inplace = True)
df.head(2)

Количество комнат     Площадь  Жилая площадь  Площадь кухни  Этаж  \
0                3.0  115.027311            NaN           10.0     4   
1                1.0   39.832524      23.169223            8.0     7   

   Количество квартир на этаже  Год постройки дома  Экология_1 Экология_2  \
0                         10.0                2014    0.075424          B   
1                          8.0                1966    0.118537          B   

  Экология_3  Социальное_1  Социальное_2  Социальное_3  Здоровье_1  \
0          B            11          3097             0         NaN   
1          B            30          6207             1      1183.0   

   Здоровье_2  Магазины_1 Магазины_2           Цена  
0           0           0          B  305018.871089  
1           1           0          B  177734.553407

10. Выведите отдельно столбец, содержащий цену, по номеру и названию. Выведите первую, десятую и предпоследнюю строку таблицы по номеру и по индексу.

In [ ]:
df['Цена']

0       305018.871089
1       177734.553407
2       282078.720850
3       168106.007630
4       343995.102962
            ...      
9995    119367.455796
9996    199715.148807
9997    165953.912580
9998    171842.411855
9999    177685.627486
Name: Цена, Length: 10000, dtype: float64

In [ ]:
print(df.iloc[0])
print()
print(df.iloc[10])
print()
print(df.iloc[-1])

Количество комнат                        3.0
Площадь                           115.027311
Жилая площадь                            NaN
Площадь кухни                           10.0
Этаж                                       4
Количество квартир на этаже             10.0
Год постройки дома                      2014
Экология_1                          0.075424
Экология_2                                 B
Экология_3                                 B
Социальное_1                              11
Социальное_2                            3097
Социальное_3                               0
Здоровье_1                               NaN
Здоровье_2                                 0
Магазины_1                                 0
Магазины_2                                 B
Цена                           305018.871089
Name: 0, dtype: object

Количество комнат                        3.0
Площадь                            74.199049
Жилая площадь                      44.735889
Площадь кухни                  

11. Выделите в отдельную таблицу последние десять строк. Уберите в ней столбец с ценой. Склейте ее с первоначальной таблицей при помощи append. Заполните отсутствующие значения цены средним по таблице.

In [ ]:
df_new1 = df.iloc[-10:]
df_new1 = df_new1.drop(['Цена'], axis = 1)
df.shape, df_new1.shape

((10000, 18), (10, 17))

In [ ]:
df1 = df.drop(df.index[-10:], axis = 0)
df_new1 = df_new1.append(df1)
df_new1

<ipython-input-135-200a3f730460>:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_new1 = df_new1.append(df1)


Количество комнат    Площадь  Жилая площадь  Площадь кухни  Этаж  \
9990                1.0  18.983962      11.419796            2.0     1   
9991                2.0  62.648779            NaN            0.0     6   
9992                2.0  50.902724      27.159548            6.0     4   
9993                3.0  84.486078      88.931509            0.0     4   
9994                1.0  43.303458      21.519087            8.0    12   
...                 ...        ...            ...            ...   ...   
9985                1.0  34.723984      19.840550            9.0     6   
9986                1.0  40.488273      23.382283            7.0     2   
9987                2.0  62.690057      64.602939           10.0    19   
9988                1.0  39.630082      22.006139            8.0     8   
9989                2.0  45.118604      33.759011            5.0     8   

      Количество квартир на этаже  Год постройки дома  Экология_1 Экология_2  \
9990                          5.0                1967    0.194489          B   
9991                         17.0                1977    0.243205          B   
9992                          9.0                1972    0.127812          B   
9993                         22.0                2016    0.007122          B   
9994                         14.0                1992    0.161532          B   
...                           ...                 ...         ...        ...   
9985                         16.0                1988    0.521867          B   
9986                          4.0                1961    0.000000          B   
9987                         22.0                2018    0.007122          B   
9988                         14.0                1990    0.161532          B   
9989                         12.0                1968    0.050756          B   

     Экология_3  Социальное_1  Социальное_2  Социальное_3  Здоровье_1  \
9990          B            47          8004             3       125.0   
9991          B             5          1564             0       540.0   
9992          B            28          7287             5       320.0   
9993          B             1           264             0         NaN   
9994          B            25          5648             1        30.0   
...         ...           ...           ...           ...         ...   
9985          B            25          6149             0         NaN   
9986          B            33          7425             1         NaN   
9987          B             1           264             0         NaN   
9988          B            25          5648             1        30.0   
9989          B            24          5469             1       145.0   

      Здоровье_2  Магазины_1 Магазины_2           Цена  
9990           3           5          B            NaN  
9991           0           0          B            NaN  
9992           1           3          B            NaN  
9993           0           1          B            NaN  
9994           2           4          B            NaN  
...          ...         ...        ...            ...  
9985           0           0          B  149649.082219  
9986           2           5          B  174542.979134  
9987           0           1          B  203908.192698  
9988           2           4          B  127641.213065  
9989           0           1          B  227361.501595  

[29990 rows x 18 columns]

In [ ]:
df_new1 = df_new1.fillna(df['Цена'].mean())
df_new1

Количество комнат    Площадь  Жилая площадь  Площадь кухни  Этаж  \
9990                1.0  18.983962      11.419796            2.0     1   
9991                2.0  62.648779  214180.317647            0.0     6   
9992                2.0  50.902724      27.159548            6.0     4   
9993                3.0  84.486078      88.931509            0.0     4   
9994                1.0  43.303458      21.519087            8.0    12   
...                 ...        ...            ...            ...   ...   
9985                1.0  34.723984      19.840550            9.0     6   
9986                1.0  40.488273      23.382283            7.0     2   
9987                2.0  62.690057      64.602939           10.0    19   
9988                1.0  39.630082      22.006139            8.0     8   
9989                2.0  45.118604      33.759011            5.0     8   

      Количество квартир на этаже  Год постройки дома  Экология_1 Экология_2  \
9990                          5.0                1967    0.194489          B   
9991                         17.0                1977    0.243205          B   
9992                          9.0                1972    0.127812          B   
9993                         22.0                2016    0.007122          B   
9994                         14.0                1992    0.161532          B   
...                           ...                 ...         ...        ...   
9985                         16.0                1988    0.521867          B   
9986                          4.0                1961    0.000000          B   
9987                         22.0                2018    0.007122          B   
9988                         14.0                1990    0.161532          B   
9989                         12.0                1968    0.050756          B   

     Экология_3  Социальное_1  Социальное_2  Социальное_3     Здоровье_1  \
9990          B            47          8004             3     125.000000   
9991          B             5          1564             0     540.000000   
9992          B            28          7287             5     320.000000   
9993          B             1           264             0  214180.317647   
9994          B            25          5648             1      30.000000   
...         ...           ...           ...           ...            ...   
9985          B            25          6149             0  214180.317647   
9986          B            33          7425             1  214180.317647   
9987          B             1           264             0  214180.317647   
9988          B            25          5648             1      30.000000   
9989          B            24          5469             1     145.000000   

      Здоровье_2  Магазины_1 Магазины_2           Цена  
9990           3           5          B  214180.317647  
9991           0           0          B  214180.317647  
9992           1           3          B  214180.317647  
9993           0           1          B  214180.317647  
9994           2           4          B  214180.317647  
...          ...         ...        ...            ...  
9985           0           0          B  149649.082219  
9986           2           5          B  174542.979134  
9987           0           1          B  203908.192698  
9988           2           4          B  127641.213065  
9989           0           1          B  227361.501595  

[29990 rows x 18 columns]

12. Выделите пять последних колонок в отдельную таблицу. Удалите в ней строки, в которых цена ниже среднего. Присоедините эту таблицу к изначальной (выберите самый подходящий тип соединения).

In [ ]:
df_new2 = df[df.columns[-5:]]
bad_indexes = df_new2[df_new2['Цена'] < df_new2['Цена'].mean()].index
df_new2 = df_new2.drop(bad_indexes, axis=0)
df_new2

Здоровье_1  Здоровье_2  Магазины_1 Магазины_2           Цена
0            NaN           0           0          B  305018.871089
2          240.0           3           1          B  282078.720850
4            NaN           0           6          B  343995.102962
7          176.0           5           5          B  326174.175191
10        2620.0           0           3          B  512797.373401
...          ...         ...         ...        ...            ...
9995         NaN           1           9          B            NaN
9996         NaN           0           0          A            NaN
9997         NaN           1           5          B            NaN
9998       125.0           3           5          B            NaN
9999         NaN           3           9          B            NaN

[3831 rows x 5 columns]

In [ ]:
pd.merge(df, df_new2, how='right')

Количество комнат     Площадь  Жилая площадь  Площадь кухни  Этаж  \
0                   3.0  115.027311            NaN           10.0     4   
1                   3.0   78.342215      47.671972           10.0     2   
2                   2.0   64.285067      38.562517            9.0    16   
3                   2.0   50.391814      32.893256            8.0     8   
4                   3.0   74.199049      44.735889           10.0     5   
...                 ...         ...            ...            ...   ...   
3828                2.0   64.307684      37.038420            9.0    13   
3829                1.0   29.648057      16.555363            5.0     3   
3830                1.0   18.983962      11.419796            2.0     1   
3831                1.0   32.330292      22.326870            5.0     3   
3832                1.0   35.815476      22.301367            6.0     9   

      Количество квартир на этаже  Год постройки дома  Экология_1 Экология_2  \
0                            10.0                2014    0.075424          B   
1                            17.0                1988    0.025609          B   
2                            16.0                1972    0.282798          B   
3                            17.0                1986    0.019509          B   
4                            14.0                2008    0.035145          B   
...                           ...                 ...         ...        ...   
3828                          0.0                1977    0.072158          B   
3829                          5.0                1958    0.460556          B   
3830                          5.0                1967    0.194489          B   
3831                          9.0                1969    0.194489          B   
3832                          9.0                1975    0.127376          B   

     Экология_3  Социальное_1  Социальное_2  Социальное_3  Здоровье_1  \
0             B            11          3097             0         NaN   
1             B            33          5261             0       240.0   
2             B            33          8667             2         NaN   
3             B            37          7687            11       176.0   
4             B            42          9292             3      2620.0   
...         ...           ...           ...           ...         ...   
3828          B             2           629             1         NaN   
3829          B            20          4386            14         NaN   
3830          B            47          8004             3       125.0   
3831          B            47          8004             3       125.0   
3832          B            43          8429             3         NaN   

      Здоровье_2  Магазины_1 Магазины_2           Цена  
0              0           0          B  305018.871089  
1              3           1          B  282078.720850  
2              0           6          B  343995.102962  
3              5           5          B  326174.175191  
4              0           3          B  512797.373401  
...          ...         ...        ...            ...  
3828           0           0          A            NaN  
3829           1           5          B            NaN  
3830           3           5          B            NaN  
3831           3           5          B            NaN  
3832           3           9          B            NaN  

[3833 rows x 18 columns]

13. Выведите таблицу, содержащую среднюю цену и количество квартир на каждом этаже из первоначального набора данных.

In [ ]:
df_new3 = df.groupby(['Количество квартир на этаже'])['Цена'].mean().to_frame().reset_index()
df_new3

Количество квартир на этаже           Цена
0                           0.0  204415.443445
1                           1.0  210420.432070
2                           2.0  194467.463449
3                           3.0  176652.101112
4                           4.0  151286.889742
5                           5.0  198875.891047
6                           6.0  254037.507036
7                           7.0  282340.913443
8                           8.0  310717.333793
9                           9.0  205722.800314
10                         10.0  249284.579609
11                         11.0  255475.395565
12                         12.0  207663.779323
13                         13.0  269808.869597
14                         14.0  228882.431741
15                         15.0  201156.018676
16                         16.0  246401.079977
17                         17.0  200854.058484
18                         18.0  228426.354875
19                         19.0  179433.629840
20                         20.0  235022.735795
21                         21.0  305127.093448
22                         22.0  254116.009497
23                         23.0  326630.692549
24                         24.0  251162.190732
25                         25.0  205644.073077
26                         26.0  244668.613410
27                         27.0  291783.959020
28                         28.0  248459.724788
29                         29.0  131477.022922
30                         30.0  354135.918321
31                         31.0  287326.123905
32                         32.0  175558.742946
33                         36.0  342223.033781
34                         37.0  285613.082870
35                         38.0  269113.584248
36                         39.0  335364.930260
37                         40.0  499438.961487
38                         44.0  117647.461002
39                         45.0  213171.135199
40                         47.0  450706.552655
41                         48.0  295544.012900
42                         99.0  269728.514047
43                        117.0  207248.370520

14. Сохраните получившуюся таблицу в файлы формата csv и xlsx. Прочитайте их и убедитесь, что данные отображаются корректно.

In [ ]:
df_new3.to_csv('/content/drive/MyDrive/мо/df_new3.csv', sep=';', encoding='utf-8-sig')

15. Создайте в Excel или другом табличном редакторе таблицу, содержащую несколько численных и текстовых полей. Прочитайте ее в программу при помощи pandas.

16. Дальнейшие задания производите используя изначальную версию датасета. Должны быть подписаны названия графиков, названия осей, указаны значения на осях. Оцениваться будет использование количества различных атрибутов при построении графиков и визуальная красота.

17. Постройте круговую диаграмму для признака Rooms, иллюстрирующую количество квартир в процентах в зависимости от количества комнат. Сделайте сектор с наибольшим числом квартир выдвинутым.

18. Постройте гистограмму по целевой переменной Price. Оцените визуально, по какой цене продаётся наибольшее количество квартир.

19. Постройте диаграммы рассеяния для признаков Rooms, Square, HouseFloor, HouseYear в зависимости от целевой переменной Price в одной области figure. Оцените визуально, есть ли среди них такие, на которых разброс точек близок к линейной функции.

20. Постройте ядерную оценку плотности целевой переменной Price. Оцените визуально, напоминает ли полученный график нормальное распределение. Постройте двумерную ядерную оценку плотности для целевой переменной Price и признака HouseFloor, затем оцените визуально на каких этажах и по какой цене продаётся основная масса квартир.

21. Постройте ящиковую диаграмму признака Square. Оцените визуально имеются ли выбросы, и, если да, то начиная с какого размера площади значение признака можно считать выбросом.

22. При помощи сетки графиков PairGrid визуализируйте попарные отношения признаков Rooms, Square, HouseFloor, HouseYear, Price следующим образом: на диагонали - гистограммы, под диагональю - ядерные оценки плотности, над диагональю - диаграммы рассеяния. По результатам визуализации сделайте выводы.

23. Постройте тепловую карту матрицы корреляции (df.corr()) признаков Rooms, Square, HouseFloor, HouseYear, Price. По ней определите, какие признаки являются зависимыми (у таких признаков коэффициент корреляции близок к единице).